# Generated by Django 3.0.3 on 2020-03-27 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_name', models.CharField(max_length=200)),
                ('region_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=20)),
                ('start_depth', models.IntegerField(default=0)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbdb.Expedition')),
            ],
        ),
    ]
