# Generated by Django 3.0.3 on 2020-03-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='start_depth',
            field=models.FloatField(default=0),
        ),
    ]
