# Generated by Django 3.0.3 on 2020-03-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbdb', '0002_auto_20200328_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
